### ISSUE TITLE
Site fixes

### ISSUE THREAD

**Issue by devdrops** [zendframework/zf-mkdoc-theme#14]
Found at https://docs.zendframework.com:

* Scroll down to the bottom in some pages hides part of the navigation menu:
    * Before:
    <img width="1276" alt="before" src="https://cloud.githubusercontent.com/assets/1259313/16529363/d836db1e-3f98-11e6-9ac4-399fb0a4600b.png">

    * After:
    <img width="1277" alt="after" src="https://cloud.githubusercontent.com/assets/1259313/16529373/e12f0020-3f98-11e6-902d-14a1a5409b8b.png">

* `Home` always point to the same page instead of index, as well as the breadcrumb `DOCS` step (there is no link to the Docs index page, except at the footer):
    * Detail:    
    <img width="487" alt="home" src="https://cloud.githubusercontent.com/assets/1259313/16529381/e9dbd3ce-3f98-11e6-9c27-977635fc49e4.png">

**Comment by weierophinney** [comment]
> Scroll down to the bottom in some pages hides part of the navigation menu

This is on purpose; before, the navigation menu was overlaying the footer, and, because it's transparent, made it unreadable! We figured scrolling under the footer made more sense in this case.

> Home always point to the same page instead of index

Also on purpose. The "Components" button gives the same information as is on the docs home page, and we wanted the icon to link to the ZF site itself. The word next to the logo is the specific component name ("zend-validator" in your screenshots), and links to the index for the given component.

> as well as the breadcrumb DOCS step (there is no link to the Docs index page, except at the footer):

This should likely be the component name! I'll make that change now, but may wait to push it out to all repos until a few more changes are ready as well.

Thanks for the feedback!
